# Generated by Django 2.0.2 on 2018-03-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('customer_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('product_id', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('status_code', models.IntegerField(choices=[(0, 'Charged'), (1, 'Attempting'), (2, 'Failed')])),
                ('status_text', models.TextField(blank=True, default=None, null=True)),
                ('firstattempt', models.DateField(blank=True, default=None, null=True)),
                ('secondattempt', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
