# Generated by Django 2.0.2 on 2018-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_csvrecord_scheduled_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecord',
            name='scheduled_date',
            field=models.DateField(),
        ),
    ]
