# Generated by Django 2.0.2 on 2018-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180302_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvrecord',
            name='scheduled_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
