# Generated by Django 2.0.2 on 2018-03-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180302_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvrecord',
            name='expiration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
