# Generated by Django 2.0.2 on 2018-03-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_csvrecord_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvrecord',
            name='action_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='csvrecord',
            name='last_modified_by',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
